/* Generated by index-editor.html */
window.HOME_DATA = {
  "name": "Zhiheng He",
  "location": "[City]",
  "headlineFirst": "",
  "headlineEmphasis": "",
  "intro": "I am First Last, a [position] at [institution]. My work explores how [your primary research topic] shapes the ways we understand the world.",
  "portrait": "",
  "portraitLabel": "YOUR\nPORTRAIT",
  "portraitCaption": "Replace with a personal photo in assets/images/",
  "email": "hez@ruc.edu.cn",
  "cvUrl": "assets/CV.pdf",
  "news": [
    {
      "date": "2026.06",
      "text": "[A paper title] has been accepted to [Conference / Journal]."
    },
    {
      "date": "2026.04",
      "text": "I will present [project title] at [Event name]."
    },
    {
      "date": "2026.01",
      "text": "Delighted to receive the [Award name]."
    }
  ]
};
